#!/usr/bin/env bash
# Canonical suite registry. The caller supplies a callback receiving ID, label, and command.

suite_registry() {
  local callback="$1"
  "$callback" linear "Linear reconciler regression suite" python3 "$ROOT/ci/linear-sync-test.py"
  "$callback" effective-ticket "effective ticket overlay suite" python3 "$ROOT/ci/effective-ticket-test.py"
  "$callback" ledger "runtime ledger regression suite" python3 "$ROOT/ci/ledger-view-test.py"
  "$callback" attempt-cancel "targeted attempt cancellation suite" python3 "$ROOT/ci/attempt-cancel-test.py"
  "$callback" provider-executor "isolated provider executor suite" python3 "$ROOT/ci/provider-executor-test.py"
  "$callback" provider-activation "isolated provider activation suite" python3 "$ROOT/ci/provider-activation-test.py"
  "$callback" provider-artifact-controller "provider artifact controller suite" python3 "$ROOT/ci/provider-artifact-controller-test.py"
  "$callback" provider-coordinator "provider coordinator concurrency suite" python3 "$ROOT/ci/provider-coordinator-test.py"
  "$callback" provider-credential-broker "provider credential broker security suite" python3 "$ROOT/ci/provider-credential-broker-test.py"
  "$callback" provider-recovery "provider recovery and rollback suite" python3 "$ROOT/ci/provider-recovery-test.py"
  "$callback" provider-runtime "transactional provider runtime suite" python3 "$ROOT/ci/provider-runtime-test.py"
  "$callback" dispatch-plan "autonomous dispatch planner suite" python3 "$ROOT/ci/dispatch-plan-test.py"
  "$callback" factory-controller "non-agent reconciliation controller suite" python3 "$ROOT/ci/factory-controller-test.py"
  "$callback" certification-runner "measured certification DAG suite" python3 "$ROOT/ci/certification-runner-test.py"
  "$callback" state-machine "deterministic state-machine suite" python3 "$ROOT/ci/state-machine-test.py"
  "$callback" progress-timeout "authenticated progress timeout suite" python3 "$ROOT/ci/progress-timeout-test.py"
  "$callback" ticket-passport "authenticated ticket passport suite" python3 "$ROOT/ci/ticket-passport-test.py"
  "$callback" publication-lease "serialized publication lease suite" python3 "$ROOT/ci/publication-lease-test.py"
  "$callback" publication-conflict-policy "fail-closed publication conflict suite" python3 "$ROOT/ci/publication-conflict-policy-test.py"
  "$callback" publication-repair "typed publication repair suite" python3 "$ROOT/ci/publication-repair-test.py"
  "$callback" ci-rerun "same-head transient CI rerun suite" python3 "$ROOT/ci/ci-rerun-test.py"
  "$callback" qualification-reducer "exact qualification evidence reducer suite" python3 "$ROOT/ci/qualification-reducer-test.py"
  "$callback" qualification-environment "sealed live qualification environment suite" python3 "$ROOT/ci/qualification-environment-test.py"
  "$callback" budget-stage "budget-only delivery stop suite" python3 "$ROOT/ci/budget-stage-test.py"
  "$callback" ticket-pr "early ticket PR suite" python3 "$ROOT/ci/ticket-pr-test.py"
  "$callback" operator-console "operator console security suite" python3 "$ROOT/ci/operator-console-test.py"
  "$callback" model-router "model router regression suite" python3 "$ROOT/ci/model-router-test.py"
  "$callback" model-manager "model manager regression suite" python3 "$ROOT/ci/model-manager-test.py"
  "$callback" model-control "model control regression suite" python3 "$ROOT/ci/model-control-test.py"
  "$callback" envelope-control "envelope control regression suite" python3 "$ROOT/ci/envelope-control-test.py"
  "$callback" claude-kimi "disabled Claude Kimi adapter suite" python3 "$ROOT/ci/claude-kimi-adapter-test.py"
  "$callback" failed-handoff "failed-attempt handoff suite" python3 "$ROOT/ci/failed-attempt-handoff-test.py"
  "$callback" fallback-approval "model fallback approval suite" python3 "$ROOT/ci/model-fallback-approval-test.py"
  "$callback" model-fallback "model fallback transaction suite" python3 "$ROOT/ci/model-fallback-test.py"
  "$callback" ci-scope "selective CI scope" bash "$ROOT/ci/ci-scope-test.sh"
  "$callback" process-group-readiness "process-group readiness suite" python3 "$ROOT/ci/run-in-process-group-test.py"
  "$callback" factory-scripts "factory script regression suite" bash "$ROOT/ci/test-factory-scripts.sh"
  "$callback" dispatch-leases "dispatcher lease suite" bash "$ROOT/ci/dispatch-leases-test.sh"
  "$callback" reorder-test-fixes "reorder test-fixes suite" bash "$ROOT/ci/reorder-test-fixes-test.sh"
  "$callback" preflight "preflight suite" bash "$ROOT/ci/preflight-test.sh"
  "$callback" ticket-state "ticket-state suite" bash "$ROOT/ci/ticket-state-test.sh"
  "$callback" ticket-attest "ticket attestation suite" python3 "$ROOT/ci/ticket-attest-test.py"
  "$callback" legacy-closeout "legacy closeout suite" python3 "$ROOT/ci/legacy-closeout-test.py"
  "$callback" terminal-backfill "terminal backfill suite" python3 "$ROOT/ci/terminal-backfill-test.py"
  "$callback" protected-merge-reconciliation "protected merge reconciliation suite" python3 "$ROOT/ci/protected-merge-reconciliation-test.py"
  "$callback" hermes-contract "Hermes contract suite" bash "$ROOT/ci/hermes-contract-test.sh"
  "$callback" factory-kit "factory kit release suite" bash "$ROOT/ci/factory-kit-test.sh"
  "$callback" factory-dev-lane "isolated factory development lane suite" bash "$ROOT/ci/factory-dev-lane-test.sh"
  "$callback" conformance "conformance app suite" run_conformance
  "$callback" immutability "test immutability suite" run_immutability
  "$callback" artifact-policy "artifact policy self-test" "$ROOT/scripts/artifact-check" --self-test
}
